### ISSUE TITLE
Reference Database preparation

### ISSUE THREAD

**Issue by NielQC** [compmetagen/strainest#2]
Hi Davide, 

I'm trying to build a custom database for _Bifidobacterium longum_, and I'm following the steps you used according to the 'Methods' section in your paper. Although I know you offer a processed database for this bacteria, I want to do it by myself cause I will need to study bacterias for which you don't provide processed database. 

I think the problem is my lack of understanding about the files format and use. I'm able to run all the steps until that where you map the 'representative genomes for the metagenome alignment' (A1, A2...) against the representative sequence (SR, chosen according to NCBI). 

`strainest mapgenomes  A1.fasta  A2.fasta  SR.fasta  MA.fasta`

The problem is I don't know which are these 'representative genomes for the metagenome alignment'. 

From your Methods section:  "iii) for each cluster, the genome with the lowest average distance from the members of its group was chosen as a representative (A1,…, A10, see Fig. 1d)."  First of all, I am not able to find a file that says which assemblies compose each cluster, then I can't select a representative assembly for every cluster. My 'clusters.txt' file doesn't seems to me to be the actual file I'm looking for, cause there are always three columns, both first with an assembly code and the third with a value, that I guess is a the distance between both assemblies. Are these assemblies indeed their cluster representant? 

I'm sure you can help me to understand this. Also, I can provide any file you want to check. 

Many thanks in advance! :smiley:

**Comment by palomo11** [comment]
Hi @NielQC,

Did you manage to solve that issue? I also would like to build my own database, but I'm having similar problems...

Thanks!

**Comment by NielQC** [comment]
Hi @palomo11, 

I was waiting until developer's answer. Seems  he's active again here, so let's see his opinion. Anyway, please let me know if you manage to build your custom database : )

**Comment by claudiodonati** [comment]
HI @NielQC, @palomo11 

First of all, I apologize for the late reply. I will try to clarify what are the main steps to build a custom database.

The procedure includes two independent clustering steps, with different thresholds and purposes. Both are done using hierarchical clustering (complete linkage) from the mash.dist distance matrix computed using mash.

1) The first is intended to remove very similar sequences, and produce a list of representative sequences (R1, …, RN) that will be used to build the reference SNV profiles. These profiles will be used as basis for the penalized fitting using lasso. The number of N is not preset, and depends on the genomic variability of the species. In the paper we have usually chosen a clustering radius of 0.1% mash distance (~99.9% ANI). This threshold defines the maximum resolution of the algorithm, i.e. if you have two isolates within this threshold in your sample StrainEst will collapse them into one strain.

2) The second is to select a smaller set of sequences to align the metagenomic reads against. We do not want to use a single reference, because you could bias your results against strains that are too divergent from the reference only because the reads do not align. We have found that 10 sequences are usually enough. Again, these were determined using hierarchical clustering fixing the number of clusters.

We did not provide a script to perform these two steps, leaving the preparation of the two sequence databases to the user. The main reason was that it is difficult to develop something that works on all species that might have very different population structure. In addition, in some cases you might want to define your reference strains manually, for instance if you want to link to existing epidemiological literature (e.g. the Sequence Types of the Multi Locus Sequence Typing schema). 

However, we are now testing an utility that will perform all these preliminary steps automatically and prepare the databases for you. This will be released shortly, as soon as we finish the testing phase. However, I want to stress that you will always have to check that the results, in term of core genome, number of SNVs and number of reference profiles are sensible, because sometimes you can get unexpected results especially if named species contain subspecies that are distantly related in term of genome sequences.

Hope this helps

**Comment by cirodri1** [comment]
Hello @claudiodonati !

Thank you for your detailed explanation and help! 
I was wondering if you have released the utility you mentioned in your post above back in 2018, where the preliminary steps for the creation of a database will be automated. I am trying to find such flag and I have not been able to. If you could guide me to where to find the utility and how to use it, it would be very much appreciated!
